# Generated by Django 4.1.3 on 2023-01-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_customer_review'),
        ('orders', '0005_alter_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.customer'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
