# Generated by Django 4.1.3 on 2023-02-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_paymentmethods_remove_order_complete_order_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='PaymentMethod',
        ),
    ]
