# Generated by Django 4.1.3 on 2022-11-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoryKey',
        ),
    ]
